# Jekyll Configuration
theme: jekyll-theme-minimal
title: Yulun Zhuang
description: Undergraduate at SUSTech, China
logo: img/logo2.jpg
url_cv: /docs/Arno_s_Resume.pdf
url_github: https://github.com/silvery107
url_email: z1079931505@gmail.com
icon: img/logo_square.ico
