# Jekyll Configuration
theme: jekyll-theme-minimal
title: Yulun Zhuang
description: Undergraduate at SUSTech, China
logo: img/logo2.jpg
google_analytics: G-H2H5LCSDZ9
url_cv: /docs/Arno_s_Resume.pdf
url_github: https://github.com/silvery107
url_email: z1079931505@gmail.com
url_linkedin: https://www.linkedin.com/in/yulun-arno-zhuang-744735173/
icon: img/logo_square.ico
