# Jekyll Configuration
theme: jekyll-theme-minimal

# Basic Information
title: Mehdi Zarei
description: 
logo: assets/img/cartoon_avatar_high_res.png 

# Contact & Social Links
url_github: https://github.com/mehdizareii79
url_email: zmehdi734@gmail.com
url_linkedin: -
url_steam: -
url_scholar: -
# url_cv: docs/CV_Yulun_Zhuang.pdf

# Optional Settings
chinese_name: 
google_analytics: 
