# Jekyll Configuration
theme: jekyll-theme-minimal
title: Yulun Zhuang
description: B.Eng from SUSTech
logo: img/logo2.jpg
google_analytics: G-H2H5LCSDZ9
url_cv: /docs/Arno_s_Resume.pdf
url_github: https://github.com/silvery107
url_email: z1079931505@gmail.com
icon: img/logo.jpg