# Jekyll Configuration
theme: jekyll-theme-minimal

# Basic Information
title: Mehdi Zarei
description: Prospective PhD student in Control and Robotics
logo: assets/img/cartoon_avatar_high_res.png 

# Contact & Social Links
url_github: https://github.com/mehdizareii79
url_email: zmehdi734@gmail.com
url_linkedin: https://www.linkedin.com/in/mehdi-zarei-1a94a0173/
url_steam: https://steamcommunity.com/profiles/76561198180262991/
url_scholar: 
# url_cv: docs/CV_Yulun_Zhuang.pdf

# Optional Settings
chinese_name: 
google_analytics: 
