# Jekyll Configuration
theme: jekyll-theme-minimal
title: Yulun Zhuang
description: Robotics UG at SUSTech
logo: assets/img/head.png
google_analytics: G-H2H5LCSDZ9
url_cv: /docs/CV_Yulun_Zhuang.pdf
url_github: https://github.com/silvery107
url_email: z1079931505@gmail.com
url_linkedin: https://www.linkedin.com/in/yulun107
# icon: assets/img/logo_square.ico
